config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  resources :users
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :distributors, except: [:destroy]
  resources :in_invoices, path: 'invoices', except: [:destroy] do
    member do
      get :toggle_status
    end
  end
  resources :canteen_reports, except: [:show]
  resources :bank_deposits, except: [:show, :destroy]
end

app/models/distributor.rb
class Distributor < ApplicationRecord
  has_many :in_invoices
  validates_presence_of :name
end

app/controllers/distributors_controller.rb
class DistributorsController < ApplicationController
  before_action :logged_in_user
  before_action :set_distributor, only: [:show, :edit, :update]

  def index
    @distributors = Distributor.all
  end

  def show

  end

  def new
    @distributor = Distributor.new
  end

  def create
    @distributor = Distributor.new(distributor_params)
    if @distributor.save
      redirect_to distributor_path(@distributor)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @distributor.update(distributor_params)
      redirect_to distributor_path(@distributor)
    else
      render :edit
    end
  end

  private

  def set_distributor
    @distributor = Distributor.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def distributor_params
    params.require(:distributor).permit(:name)
  end

  def logged_in_user
     unless logged_in? && current_user.admin?
       flash[:danger] = "Only admins can view this page"
       redirect_to root_url
     end
   end

end

app/views/distributors/_form.html.erb
<%= form_for(distributor) do |f| %>
<div class="container">
  <div class="col-md-4">
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
    </div>

    <div class="col-md-6">
      <%= f.submit "Submit", class: "btn btn-success-outline btn-block" %>
    </div>
    <div class="col-md-6">
      <%= link_to 'Cancel', distributors_path, class: "btn btn-danger-outline btn-block" %>
    </div>

    </div>
  </div>
<% end %>

app/views/distributors/edit.html.erb
<h1>New Distributor</h1>

<%= render 'form', distributor: @distributor %>

app/views/distributors/index.html.erb
<h2 class="dashhead-title">DISTRIBUTORS</h2>
<h1><%= link_to 'New Distributor', new_distributor_path, class: "btn btn-success-outline" %></h1>
<div class="row">
  <% @distributors.each do |distributor| %>
    <div class="col-md-6 p-a-md">
      <div class="statcard-primary">
        <div class="p-a">
          <h2 class="statcard-desc text-center">
            <%= distributor.name %>
          </h2>
          <hr class="statcard-hr">
          <h4 class="statcard-number">
            Total Amount :
            <span class="statcard-number"><%= fa_icon "euro" %><%= distributor.in_invoices.sum('amount') %></span>
          </h4>
          <hr class="statcard-hr">
          <h4 class="statcard-number">
            Paid Amount :
            <span class="statcard-number"><%= fa_icon "euro" %><%= distributor.in_invoices.paid.sum('amount') %></span>
          </h4>
          <hr class="statcard-hr">
          <h4 class="statcard-number">
            Pending Amount :
            <span class="statcard-number"><%= fa_icon "euro" %><%= distributor.in_invoices.pending.sum('amount') %></span>
          </h4>
        </div>
        <div class="statcard statcard-warning text-center">
          <div class="p-a">
            <%= link_to 'Show', distributor, class: "btn btn-pill btn-info" %>
            <%= link_to 'Edit', edit_distributor_path(distributor),class: "btn btn-pill btn-success" %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/distributors/new.html.erb
<h1>New Distributor</h1>

<%= render 'form', distributor: @distributor %>

app/views/distributors/show.html.erb
<h1 class="text-center"><%= @distributor.name %></h1>
<% @distributor.in_invoices.each do |invoice| %>
<div class="col-md-6 p-a-md">
    <div class="<%='statcard statcard-danger' if invoice.pending?%> <%='statcard statcard-success' if invoice.paid?%>">
      <div class="p-a">
        <h4 class="statcard-desc text-center">
        <%= invoice.invoice_number %></h4>
        <hr class="statcard-hr">

          <h4 class="statcard-number">
            Description :
            <span class="statcard-number"><%= invoice.description.upcase %></span>
          </h4>
          <br>
          <h4 class="statcard-number">
            Amount :
            <span class="statcard-number"><%= fa_icon "euro" %> <%= invoice.amount %></span>
          </h4>
      </div>
      <div class="statcard statcard-warning text-center">

        <div class="p-a">
      <%= link_to 'EDIT', edit_in_invoice_path(invoice), class: "btn btn-pill btn-info" %>
      <%= link_to invoice.status.upcase, toggle_status_in_invoice_path(invoice), data: { confirm: 'Are you sure?'}, class: "btn btn-pill btn-primary"  %>

    </div>
    </div>
    </div>

  </div>
  <% end %>
  <div class="row">
    <div class="col-md-6 p-a-md">
      <%= link_to distributors_path, class: "btn btn-default-outline" do %>
      <%= fa_icon 'chevron-left' %>
      BACK
      <% end %>
    </div>
  </div>