config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  resources :users
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :distributors, except: [:destroy]
  resources :in_invoices, path: 'invoices', except: [:destroy] do
    member do
      get :toggle_status
    end
  end
  resources :canteen_reports, except: [:show]
  resources :bank_deposits, except: [:show, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  enum roles: { admin: 0, coach: 1 }
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  validates :roles, presence: true
  class << self
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                    BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user
  before_action :correct_user,   only: [:show, :edit, :update]
  before_action :admin_user, only: [:index, :new, :create, :destroy]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)    # Not the final implementation!
    if @user.save
      flash[:success] = "New User Created"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end


  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  private

   def user_params
     params.require(:user).permit(:name, :email, :password,
                                  :password_confirmation, :roles)
   end

   def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
   end

   def correct_user
     @user = User.find(params[:id])
     if !logged_in? || (logged_in? and current_user != @user and !current_user.admin?)
       flash[:danger] = "You can only edit or delete your account"
       redirect_to users_path
     end
   end

   def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
     gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
     size = options[:size]
     gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
     image_tag(gravatar_url, alt: user.name, class: "gravatar")
   end
   def gravatar_for_sidebar(user, options = { size: 30 })
      gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
      size = options[:size]
      gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
      image_tag(gravatar_url, alt: user.name, class: "img-circle")
    end
end

app/views/users/_user.html.erb
<tr>
  <td>
    <%= user.name.upcase %>
  </td>
  <td class="text-center">
    <span class="badge"><%= user.roles.upcase %></span>
  </td>

  <td class="text-center">
    <%= link_to "UPDATE", edit_user_path(user), class: "btn btn-xs btn-pill btn-warning-outline" %>
  </td>

    <td class="text-center">
      <% if current_user.admin? && !current_user?(user) %>
     <%= link_to "DELETE", user, class: "btn btn-xs btn-pill btn-danger-outline", method: :delete,
                                  data: { confirm: "You sure?" } %>
    <% end %>
    </td>
</tr>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Edit User</h1>
<div class="form-group">
  <div class="gravatar_edit">
    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails" target="_blank">change</a>
  </div>
</div>
<div class="row">
  <div class="col-md-6">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>
      <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      </div>
      <div class="form-group">
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
      </div>
      <div class="form-group">
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>
      </div>
      <div class="form-group">
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
      <% if logged_in? && current_user.admin? %>
      <div class="form-group">
      <%= f.label :roles, "Role" %>

        <%= f.select(:roles, User.roles.keys.map {|roles| [roles.titleize,roles]}, {prompt: "Select Role"}, {class: "form-control"})%>


      </div>
      <% end %>
      <div class="actions">
        <%= f.submit "Save changes", class: "btn btn-primary-outline btn-block" %>
      </div>

    <% end %>

  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'USERS') %>
<h2>USERS</h2>

<h1><%= link_to 'New User', new_user_path, class: "btn btn-success-outline" %></h1>

<div class="table-full">
  <div class="table-responsive">
  <table class="table table-bordered table-hover" data-sort="table">
    <thead>
      <tr>
        <th>Name</th>
        <th class="text-center">Role</th>
        <th colspan="2" class="text-center">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
      <%= render user %>
    <% end %>
    </tbody>
  </table>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6">

    <%= form_for(@user, url: signup_path) do |f| %>
     <%= render 'shared/error_messages' %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control"  %>
      </div>
      <div class="form-group">
      <%= f.label :email %>
      <%= f.email_field :email, class: "form-control"  %>
      </div>
      <div class="form-group">
      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control"  %>
      </div>
      <div class="form-group">
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: "form-control"  %>
      </div>
      <div class="form-group">
      <%= f.label :roles, "Roles" %>
      <%= f.select("roles", User.roles.keys.map {|roles| [roles.titleize,roles]}, {prompt: "Select Role"}, {class: "form-control"})%>
      </div>
      <div class="actions">
        <%= f.submit "Create User", class: "btn btn-primary-outline btn-block" %>
      </div>

    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <div class="col-md-6">
    <h1>
      <%= gravatar_for @user %>
      <%= @user.name %>
    </h1>
  </div>
  <div class="col-md-6">
    <%= link_to edit_user_path(@user) do %>
    <button class="btn btn-xs btn-pill btn-warning-outline"><%= fa_icon 'cogs' %>&nbsp;
    Settings
    </button>
    <% end %>
  </div>
</div>