config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  resources :users
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :distributors, except: [:destroy]
  resources :in_invoices, path: 'invoices', except: [:destroy] do
    member do
      get :toggle_status
    end
  end
  resources :canteen_reports, except: [:show]
  resources :bank_deposits, except: [:show, :destroy]
end

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_sidebar.html.erb
<% if logged_in? %>
<nav class="sidebar-nav">
          <div class="sidebar-header">
            <button class="nav-toggler nav-toggler-sm sidebar-toggler collapsed" type="button" data-toggle="collapse" data-target="#nav-toggleable-sm" aria-expanded="false">
              <span class="sr-only">Toggle nav</span>
            </button>
            <%= link_to( image_tag(('ttlogo_whitel&m.png')),  root_path, class: "sidebar-brand") %>
          </div>

          <div class="nav-toggleable-sm collapse" id="nav-toggleable-sm" aria-expanded="false" style="height: 0px;">
            <ul class="nav nav-pills nav-stacked">
              <% if logged_in? && current_user.admin? %>
              <li>
                <%= link_to distributors_path do %>
                  <span><%= fa_icon 'building-o' %></span>&nbsp;
                  Distributors
                <% end %>
              </li>
              <li>
                <%= link_to in_invoices_path do %>
                  <span><%= fa_icon 'file-text-o' %></span>&nbsp;
                  Invoices
                <% end %>
              </li>
              <li>
                <%= link_to canteen_reports_path do %>
                  <span><%= fa_icon 'home' %></span>&nbsp;
                  Canteen Reports
                <% end %>
              </li>
              <li>
                <%= link_to bank_deposits_path do %>
                  <span><%= fa_icon 'university' %></span>&nbsp;
                  Bank Deposits
                <% end %>
              </li>
              <li>
                <%= link_to users_path do %>
                  <span><%= fa_icon 'users' %></span>&nbsp;
                  Users
                <% end %>
              </li>
              <% end %>
              <% if logged_in? %>
            <hr />
            <li class="nav-header">Profile</li>
              <li>
                <%= link_to current_user do %>
                  <%= gravatar_for_sidebar current_user %>
                  <%= current_user.name %>
                <% end %>
              </li>


              <li class="divider"></li>
              <li>
                <%= link_to logout_path, method: :delete do %>
                <span><%= fa_icon 'sign-out' %></span>&nbsp;
                Log Out
              <% end %>
              </li>

              <% else %>
              <li>
                <%= link_to login_path do %>
                  <span><%= fa_icon 'sign-in' %></span>&nbsp;
                  Log In
                <% end %>
              </li>
              <% end %>
          </ul>
            <hr class="visible-xs m-t">
          </div>
        </nav>
<% end %>