config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  resources :users
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :distributors, except: [:destroy]
  resources :in_invoices, path: 'invoices', except: [:destroy] do
    member do
      get :toggle_status
    end
  end
  resources :canteen_reports, except: [:show]
  resources :bank_deposits, except: [:show, :destroy]
end

app/models/in_invoice.rb
class InInvoice < ApplicationRecord
  belongs_to :distributor
    enum status: { pending: 0, paid: 1 }
  validates_presence_of :description, :invoice_number, :amount
end

app/controllers/in_invoices_controller.rb
class InInvoicesController < ApplicationController
  before_action :logged_in_user
  before_action :set_in_invoice, only: [:show, :edit, :update, :toggle_status]

  def index
    @in_invoices = InInvoice.all
  end

  def show

  end

  def new
    @in_invoice = InInvoice.new
  end

  def create
    @in_invoice = InInvoice.new(in_invoice_params)
    if @in_invoice.save
      redirect_to @in_invoice
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @in_invoice.update(in_invoice_params)
      redirect_to @in_invoice
    else
      render :edit
    end
  end

  def toggle_status
    if @in_invoice.pending?
      @in_invoice.paid!
      flash[:success] =  'Invoice status has been Paid'
    else @in_invoice.paid?
    @in_invoice.pending!
    flash[:danger] = 'Invoice status set to Pending'
    end

    redirect_to in_invoice_url
  end


  private
    def set_in_invoice
      @in_invoice = InInvoice.find(params[:id])
    end

    def in_invoice_params
      params.require(:in_invoice).permit(:invoice_number, :description, :amount, :status, :distributor_id)
    end

    def logged_in_user
       unless logged_in? && current_user.admin?
         flash[:danger] = "Only admins can view this page"
         redirect_to root_url
       end
    end
end

app/views/in_invoices/_form.html.erb
<%= form_for(in_invoice) do |f| %>
  <% if in_invoice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(in_invoice.errors.count, "error") %> prohibited this in_invoice from being saved:</h2>

      <ul>
      <% in_invoice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="container">
  <div class="col-md-4">
    <div class="form-group">
      <%= f.label :company_id %>
      <%= f.collection_select :distributor_id, Distributor.all , :id, :name, {prompt: "Select a Company"}, {class: "form-control"} %>
    </div>
    <div class="form-group">
      <%= f.label :invoice_number %>
      <%= f.text_field :invoice_number, class: "form-control"%>
    </div>

    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_field :description, class: "form-control"%>
    </div>

    <div class="form-group">
      <%= f.label :amount %>
      <div class="input-group">
        <span class="input-group-addon">
          <span><%= fa_icon "euro" %></span>
        </span>
      <%= f.text_field :amount, class: "form-control" %>
    </div>
    </div>

    <div class="col-md-6">
      <%= f.submit "Submit", class: "btn btn-success-outline btn-block" %>
    </div>
    <div class="col-md-6">
      <%= link_to 'Cancel', in_invoices_path, class: "btn btn-danger-outline btn-block" %>
    </div>
  </div>
<% end %>
</div>

app/views/in_invoices/edit.html.erb
<h1>Editing Invoice</h1>

<%= render 'form', in_invoice: @in_invoice %>

app/views/in_invoices/index.html.erb
<h2 class="dashhead-title">INVOICES</h2>
<h1><%= link_to "New Invoice", new_in_invoice_path, class: 'btn btn-success-outline' %></h1>
<div class="table-full">
  <div class="table-responsive">
    <table class="table table-bordered table-hover" data-sort="table">
      <thead>
        <tr>
          <th class="sorter-shortDate dateFormat-ddmmyyyy">Date</th>
          <th>Company:</th>
          <th>Invoice number</th>
          <th class="text-center">Amount</th>
          <th>Status</th>
        </tr>
      </thead>

  <tbody>
    <% @in_invoices.each do |in_invoice| %>
      <tr>
        <td><%= in_invoice.created_at.strftime("%d/%m/%Y") %></td>
        <td><%= link_to in_invoice.distributor.name, distributor_path(in_invoice.distributor) %></td>
        <td><%= link_to in_invoice.invoice_number, in_invoice %></td>
        <td class="text-center"><span class="<%='badge badge-danger' if in_invoice.pending?%> <%='badge badge-success' if in_invoice.paid?%>"><%= fa_icon "euro" %><%= in_invoice.amount%></span></td>
        <td><%= link_to in_invoice.status.upcase, toggle_status_in_invoice_path(in_invoice), data: { confirm: 'Are you sure?' }, class: "btn btn-xs btn-warning-outline btn-block" %> </td>
      </tr>
    <% end %>
  </tbody>
</table>
  </div>
</div>

app/views/in_invoices/new.html.erb
<h1>New Invoice</h1>

<%= render 'form', in_invoice: @in_invoice %>

app/views/in_invoices/show.html.erb
<div class="col-md-8 p-a-md">
    <div class="<%='statcard statcard-danger' if @in_invoice.pending?%> <%='statcard statcard-success' if @in_invoice.paid?%>">
      <div class="p-a">
        <h4 class="statcard-desc text-center"><%= link_to @in_invoice.distributor.name, distributor_path(@in_invoice.distributor) %></h4>
        <hr class="statcard-hr">
        <h4 class="statcard-number">
          Invoice Number :
          <span class="statcard-number"><%= @in_invoice.invoice_number %></span>
        </h4>
        <br>
          <h4 class="statcard-number">
            Description :
            <span class="statcard-number"><%= @in_invoice.description.upcase %></span>
          </h4>
          <br>
          <h4 class="statcard-number">
            Amount :
            <span class="statcard-number"><%= fa_icon "euro" %> <%= @in_invoice.amount %></span>
          </h4>
      </div>
      <div class="statcard statcard-warning text-center">

        <div class="p-a">
      <%= link_to 'EDIT', edit_in_invoice_path(@in_invoice), class: "btn btn-pill btn-info" %>
      <%= link_to @in_invoice.status.upcase, toggle_status_in_invoice_path(@in_invoice), data: { confirm: 'Are you sure?'}, class: "btn btn-pill btn-primary"  %>
      <%= link_to 'BACK', in_invoices_path, class: "btn btn-pill btn-danger" %>
    </div>
    </div>
    </div>

  </div>